### PR TITLE
Stop Tooltip component from creating empty div

### LINKED ISSUE #260: Tooltip force open prop
Feature request:

It would be nice if the tooltip has an "open" or "show" prop to force it to display. 
This would be super helpful for development as well as mode dynamic UX ideas for showing tooltips programatically.

### LINKED ISSUE #263: Tooltip component creates empty div
I had been using the tooltip component - and per tooltip component used, it's creating an empty div

image

### PR DESCRIPTION
**Pull request by elevatebart**
closes #263
closes #260 

also add forceOpen for development and design

### CODE REVIEW

**Comment by jaimefps** [comment]
@elevatebart Seems that version 0.7.0 never was published? When I try to install it says that only 0.5.4 is available?

**Comment by jaimefps** [comment]
Screen Shot 2023-07-18 at 1 58 55 PM

**Comment by elevatebart** [comment]
I believe it is published.

https://www.npmjs.com/package/@cypress-design/react-tooltip?activeTab=versions

**Comment by jaimefps** [comment]
> I believe it is published.
> 
> https://www.npmjs.com/package/@cypress-design/react-tooltip?activeTab=versions

My mistake was that I confused `@cypress/react-tooltip` and `@cypress-design/react-tooltip`, came back to it now and was able to install, thanks.

**Pull request merged**
